# generated
name: x_ivcg2vj5vhu42hnb
on:
  workflow_dispatch:
    inputs:
      x_2vqw4hj45wpi775d:
        type: string
        required: true
  workflow_call:
    inputs:
      x_2vqw4hj45wpi775d:
        type: string
        required: true
permissions: {}
jobs:
  x_jilk5xoyaizv2pia:
    name: x_jilk5xoyaizv2pia
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    outputs:
      x_jtwrjwdzszxvmqn5: ${{ steps.run.outputs.x_jtwrjwdzszxvmqn5 }}
      x_qhzrjftie2gdj3z7: ${{ steps.run.outputs.x_qhzrjftie2gdj3z7 }}
      x_ygezsllgoy73kn53: ${{ steps.run.outputs.x_ygezsllgoy73kn53 }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_n3zr7llogolq2cub: ${{ secrets.x_rvbdflruaymvxxzf }}
          x_rnofjcthpc4qmbz7: ${{ secrets.x_bltcnyaeqb2gre7e }}
          x_zvqnm43i5urhuo64: ${{ secrets.x_qpqccuz4ji3yaemy }}
          x_2uu7eyolekmt4x6v: x_xxjslkw6j4gbaahu
          x_ddmforgnxqdgpnmy: x_jtwrjwdzszxvmqn5,x_qhzrjftie2gdj3z7,x_ygezsllgoy73kn53
          x_2vqw4hj45wpi775d: ${{ inputs.x_2vqw4hj45wpi775d }}
          x_jrftuyyzydfdnhuv: ${{ secrets.x_rgkh2ukj24pii3dd }}
          x_ea77mrl3yo2ajq4z: ${{ secrets.x_uvu5arjlpainoj3r }}
          x_pbxqpudtraqnw4pv: ${{ secrets.x_tiwyhxzvgmz7aubs }}
          x_eadwiifs2yqqofda: ${{ secrets.x_e3uu2zu57hujq2fr }}
          x_eyl3mdb4c5aeowe7: ${{ secrets.x_wj33yvzevqs75t4h }}
          x_4lb2rlicps2lhdl7: ${{ secrets.x_pijl5yt3k6bwdpez }}
          x_f4e4wdneoij4cjx7: ${{ secrets.x_ohaqlvexbottgtug }}
        run: ./.github/bin/x_ivcg2vj5vhu42hnb
  x_ecjxcxmxky5k4ofh:
    name: x_ecjxcxmxky5k4ofh
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_jilk5xoyaizv2pia
    outputs:
      x_ywp4v7adihlkqrgt: ${{ steps.run.outputs.x_ywp4v7adihlkqrgt }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_n3zr7llogolq2cub: ${{ secrets.x_rvbdflruaymvxxzf }}
          x_rnofjcthpc4qmbz7: ${{ secrets.x_bltcnyaeqb2gre7e }}
          x_zvqnm43i5urhuo64: ${{ secrets.x_qpqccuz4ji3yaemy }}
          x_2uu7eyolekmt4x6v: x_kyafin5jy646v2qy
          x_ddmforgnxqdgpnmy: x_ywp4v7adihlkqrgt
          x_6vnmn5dybaitmryv: ${{ needs.x_jilk5xoyaizv2pia.outputs.x_ygezsllgoy73kn53 }}
          x_jrftuyyzydfdnhuv: ${{ secrets.x_rgkh2ukj24pii3dd }}
          x_ea77mrl3yo2ajq4z: ${{ secrets.x_uvu5arjlpainoj3r }}
          x_eadwiifs2yqqofda: ${{ secrets.x_e3uu2zu57hujq2fr }}
          x_eyl3mdb4c5aeowe7: ${{ secrets.x_wj33yvzevqs75t4h }}
          x_4lb2rlicps2lhdl7: ${{ secrets.x_pijl5yt3k6bwdpez }}
          x_f4e4wdneoij4cjx7: ${{ secrets.x_ohaqlvexbottgtug }}
        run: ./.github/bin/x_ivcg2vj5vhu42hnb
  x_n5rmmlnvxxiajzva:
    name: x_n5rmmlnvxxiajzva
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_jilk5xoyaizv2pia
      - x_ecjxcxmxky5k4ofh
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        x_vijbjvtzsiphpxns: ${{ fromJSON(needs.x_ecjxcxmxky5k4ofh.outputs.x_ywp4v7adihlkqrgt) }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_n3zr7llogolq2cub: ${{ secrets.x_rvbdflruaymvxxzf }}
          x_rnofjcthpc4qmbz7: ${{ secrets.x_bltcnyaeqb2gre7e }}
          x_zvqnm43i5urhuo64: ${{ secrets.x_qpqccuz4ji3yaemy }}
          x_2uu7eyolekmt4x6v: x_ftuj3cdjjeox2jrz
          x_ddmforgnxqdgpnmy: ''
          x_7yjivpqmrgj5oi5h: ${{ matrix.x_vijbjvtzsiphpxns }}
          x_afatceh6p5sxwekj: ${{ needs.x_jilk5xoyaizv2pia.outputs.x_jtwrjwdzszxvmqn5 }}
          x_w2asf2isynuijchl: ${{ needs.x_jilk5xoyaizv2pia.outputs.x_ygezsllgoy73kn53 }}
          x_ykqgahhc2as3bdt6: ${{ needs.x_jilk5xoyaizv2pia.outputs.x_qhzrjftie2gdj3z7 }}
          x_jrftuyyzydfdnhuv: ${{ secrets.x_rgkh2ukj24pii3dd }}
          x_ea77mrl3yo2ajq4z: ${{ secrets.x_uvu5arjlpainoj3r }}
          x_pbxqpudtraqnw4pv: ${{ secrets.x_tiwyhxzvgmz7aubs }}
          x_eadwiifs2yqqofda: ${{ secrets.x_e3uu2zu57hujq2fr }}
          x_eyl3mdb4c5aeowe7: ${{ secrets.x_wj33yvzevqs75t4h }}
          x_4lb2rlicps2lhdl7: ${{ secrets.x_pijl5yt3k6bwdpez }}
          x_f4e4wdneoij4cjx7: ${{ secrets.x_ohaqlvexbottgtug }}
        run: ./.github/bin/x_ivcg2vj5vhu42hnb
  x_pbneetkpyiy46j4d:
    name: x_pbneetkpyiy46j4d
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    permissions:
      actions: write
      contents: read
      id-token: write
    needs:
      - x_jilk5xoyaizv2pia
      - x_n5rmmlnvxxiajzva
    if: ${{ always() }}
    steps:
      - id: setup
        name: run
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - id: run
        name: run
        env:
          GITHUB_TOKEN: ${{ github.token }}
          x_n3zr7llogolq2cub: ${{ secrets.x_rvbdflruaymvxxzf }}
          x_rnofjcthpc4qmbz7: ${{ secrets.x_bltcnyaeqb2gre7e }}
          x_zvqnm43i5urhuo64: ${{ secrets.x_qpqccuz4ji3yaemy }}
          x_2uu7eyolekmt4x6v: x_btybhjybcgpt6zmf
          x_ddmforgnxqdgpnmy: ''
          x_2dyocuwgdfqhzqkh: ${{ needs.x_n5rmmlnvxxiajzva.result }}
          x_f7k735lfzu36hch3: ${{ needs.x_jilk5xoyaizv2pia.outputs.x_qhzrjftie2gdj3z7 }}
          x_nwm5ioydgoqd7scv: ${{ needs.x_jilk5xoyaizv2pia.outputs.x_jtwrjwdzszxvmqn5 }}
          x_ta3mt3e4te2ibzvc: ${{ needs.x_jilk5xoyaizv2pia.outputs.x_ygezsllgoy73kn53 }}
          x_jrftuyyzydfdnhuv: ${{ secrets.x_rgkh2ukj24pii3dd }}
          x_ea77mrl3yo2ajq4z: ${{ secrets.x_uvu5arjlpainoj3r }}
          x_eadwiifs2yqqofda: ${{ secrets.x_e3uu2zu57hujq2fr }}
          x_eyl3mdb4c5aeowe7: ${{ secrets.x_wj33yvzevqs75t4h }}
          x_4lb2rlicps2lhdl7: ${{ secrets.x_pijl5yt3k6bwdpez }}
          x_f4e4wdneoij4cjx7: ${{ secrets.x_ohaqlvexbottgtug }}
        run: ./.github/bin/x_ivcg2vj5vhu42hnb
concurrency:
  group: x_ivcg2vj5vhu42hnb
  cancel-in-progress: false
